import { Poppins } from 'next/font/google'
import './globals.css'
import AppConfigProvider from '@/providers/app-config-provider'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const poppins = Poppins({
  subsets: ['latin'],
  weight: '400',
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <AppConfigProvider>{children}</AppConfigProvider>
      </body>
    </html>
  )
}
