export const capacityPlanningData = [
  {
    name: 'Alice Johnson',
    month_projection: 120.5,
    capacity: 100.0,
    percentage: 83.2,
    mandays_needed: 22,
    additional_manpower_needed: 1,
  },
  {
    name: 'Bob Smith',
    month_projection: 95.0,
    capacity: 100.0,
    percentage: 95.0,
    mandays_needed: 20,
    additional_manpower_needed: 0,
  },
  {
    name: 'Charlie Lee',
    month_projection: 150.0,
    capacity: 110.0,
    percentage: 136.4,
    mandays_needed: 28,
    additional_manpower_needed: 2,
  },
  {
    name: 'Diana Adams',
    month_projection: 85.0,
    capacity: 90.0,
    percentage: 94.4,
    mandays_needed: 18,
    additional_manpower_needed: 0,
  },
  {
    name: 'Edward Green',
    month_projection: 200.0,
    capacity: 130.0,
    percentage: 153.8,
    mandays_needed: 35,
    additional_manpower_needed: 3,
  },
  {
    name: 'Fiona White',
    month_projection: 110.5,
    capacity: 105.0,
    percentage: 105.2,
    mandays_needed: 23,
    additional_manpower_needed: 1,
  },
  {
    name: 'George Black',
    month_projection: 98.0,
    capacity: 120.0,
    percentage: 81.7,
    mandays_needed: 19,
    additional_manpower_needed: 0,
  },
  {
    name: 'Hannah Brown',
    month_projection: 130.0,
    capacity: 100.0,
    percentage: 130.0,
    mandays_needed: 25,
    additional_manpower_needed: 1,
  },
  {
    name: 'Ian Silver',
    month_projection: 75.0,
    capacity: 95.0,
    percentage: 78.9,
    mandays_needed: 17,
    additional_manpower_needed: 0,
  },
  {
    name: 'Jane Miller',
    month_projection: 160.0,
    capacity: 120.0,
    percentage: 133.3,
    mandays_needed: 30,
    additional_manpower_needed: 2,
  },
]
