'use client'

const mockProjects = [
  {
    name: 'Website Redesign',
    type: 'Internal',
    category: 'UI/UX',
    start_date: '2025-01-10',
    end_date: '2025-03-15',
    project_owner: 'Alice Johnson',
    status: 'In Progress',
    progress: 60,
    note: 'Waiting for final design approval',
  },
  {
    name: 'Marketing Campaign Q1',
    type: 'Client',
    category: 'Marketing',
    start_date: '2025-01-05',
    end_date: '2025-02-20',
    project_owner: 'Bob Smith',
    status: 'Completed',
    progress: 100,
    note: 'Successfully launched',
  },
  {
    name: 'Mobile App Launch',
    type: 'Client',
    category: 'Development',
    start_date: '2025-02-01',
    end_date: '2025-05-30',
    project_owner: 'Charlie Lee',
    status: 'In Progress',
    progress: 45,
    note: 'Backend integration ongoing',
  },
  {
    name: 'Data Migration',
    type: 'Internal',
    category: 'IT',
    start_date: '2025-01-15',
    end_date: '2025-02-28',
    project_owner: 'Diana Adams',
    status: 'Delayed',
    progress: 30,
    note: 'Issues with legacy system',
  },
  {
    name: 'Customer Portal Upgrade',
    type: 'Client',
    category: 'Development',
    start_date: '2025-03-01',
    end_date: '2025-06-01',
    project_owner: 'Edward Green',
    status: 'Not Started',
    progress: 0,
    note: 'Pending client approval',
  },
  {
    name: 'SEO Optimization',
    type: 'Internal',
    category: 'Marketing',
    start_date: '2025-01-25',
    end_date: '2025-02-28',
    project_owner: 'Fiona White',
    status: 'Completed',
    progress: 100,
    note: 'Traffic improved by 25%',
  },
  {
    name: 'Security Audit',
    type: 'Internal',
    category: 'IT',
    start_date: '2025-02-10',
    end_date: '2025-02-20',
    project_owner: 'George Black',
    status: 'Completed',
    progress: 100,
    note: 'No critical issues found',
  },
  {
    name: 'Cloud Migration',
    type: 'Client',
    category: 'Infrastructure',
    start_date: '2025-01-20',
    end_date: '2025-04-10',
    project_owner: 'Hannah Brown',
    status: 'In Progress',
    progress: 70,
    note: 'Phase 2 in progress',
  },
  {
    name: 'Training Program',
    type: 'Internal',
    category: 'HR',
    start_date: '2025-03-05',
    end_date: '2025-03-25',
    project_owner: 'Ian Silver',
    status: 'Not Started',
    progress: 0,
    note: 'Sessions being scheduled',
  },
  {
    name: 'Product Launch',
    type: 'Client',
    category: 'Sales',
    start_date: '2025-04-01',
    end_date: '2025-05-10',
    project_owner: 'Jane Miller',
    status: 'Planning',
    progress: 10,
    note: 'Initial marketing strategy in review',
  },
]

export { mockProjects }
