'use client'

export const mocksTasks = [
  {
    _id: '6816f4c02398e8a9b92bd83c',
    assignee_ids: [
      {
        id: 'Io5FmFfpo4zmv2wp',
        name: 'Fauzan',
      },
      {
        id: 'Z3NmnmiO9OCZMokc',
        name: 'Aziza',
      },
    ],
    attachments: [],
    created_at: 1746334912542,
    created_by: 0,
    date_end: 1746637200000,
    date_start: 1746637200000,
    description: {
      blocks: [
        {
          data: {
            text: 'OKE',
          },
          id: 'c4t4MBiO5g',
          type: 'paragraph',
        },
      ],
      time: 1746334912093,
      version: '2.31.0-rc.7',
    },
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'fUTZqe2fqJpe9yQP',
    list_ids: [
      {
        id: 'kAa0ghxJLX1mKbgO',
        name: 'Research and Dev',
      },
    ],
    list_ids_text: ['asdfb3r3', 'kAa0ghxJLX1mKbgO'],
    name: 'TEST 4',
    parent_task_id: '0',
    priority_id: {
      color: '#D51616',
      id: 'hfqHjVUhRLQyBezK',
      name: 'HIGH',
    },
    product_id: {
      color: '#9C13D2',
      id: '1OBzdu6cBSVK7pZ9',
      name: 'OFFICELESS',
    },
    progress: 0,
    status_id: {
      color: '#000000',
      id: 'lNRkDKdPXq53iV94',
      name: 'BACKLOG',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746336549741,
    updated_by: 178566,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '68170d4b2398e8a9b956a469',
    assignee_ids: [
      {
        id: 'MWzxqxyqUTYCnSL9',
        name: 'Alex',
      },
    ],
    attachments: [],
    created_at: 1746341195740,
    created_by: 0,
    date_end: 1746723600000,
    date_start: 1746032400000,
    description: {
      blocks: [],
      time: 1746341195388,
      version: '2.31.0-rc.7',
    },
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'MWzxPyRIy98Bnw05',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
    ],
    name: 'task 5',
    parent_task_id: 'fUTZqe2fqJpe9yQP',
    priority_id: {
      color: '#D51616',
      id: 'hfqHjVUhRLQyBezK',
      name: 'HIGH',
    },
    product_id: {
      color: '#D23013',
      id: 'uhbRY6DSirLf2f3s',
      name: 'TALENTA',
    },
    progress: 0,
    status_id: {
      color: '#000000',
      id: 'lNRkDKdPXq53iV94',
      name: 'BACKLOG',
    },
    task_type_id: {
      color: '#D5D516',
      id: 'B93VwVE9n4S8jWFu',
      name: 'Meetings',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746341195740,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '681722102398e8a9b97c87e4',
    assignee_ids: [
      {
        id: 'MWzxqxyqUTYCnSL9',
        name: 'Alex',
      },
    ],
    created_at: 1746346512120,
    created_by: 0,
    date_end: 1746810000000,
    date_start: 1746032400000,
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'miAUQClaqgskx6P7',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
    ],
    name: 'Test 2',
    parent_task_id: '0',
    priority_id: {
      color: '#D51616',
      id: 'hfqHjVUhRLQyBezK',
      name: 'HIGH',
    },
    product_id: {
      color: '#9C13D2',
      id: '1OBzdu6cBSVK7pZ9',
      name: 'OFFICELESS',
    },
    progress: 0,
    status_id: {
      color: '#000000',
      id: 'lNRkDKdPXq53iV94',
      name: 'BACKLOG',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746346512120,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '6817226a2398e8a9b97e6b62',
    assignee_ids: [
      {
        id: 'Io5FmFfpo4zmv2wp',
        name: 'Fauzan',
      },
    ],
    created_at: 1746346602526,
    created_by: 0,
    date_end: 1746723600000,
    date_start: 1746118800000,
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'Fp7n1wNB5kd4G2sq',
    list_ids: [
      {
        id: 'kAa0ghxJLX1mKbgO',
        name: 'Research and Dev',
      },
    ],
    name: 'task 99',
    parent_task_id: 'wG0bnsxFdyijfUaN',
    priority_id: {
      color: '#D51616',
      id: 'hfqHjVUhRLQyBezK',
      name: 'HIGH',
    },
    product_id: {
      color: '#9C13D2',
      id: '1OBzdu6cBSVK7pZ9',
      name: 'OFFICELESS',
    },
    progress: 0,
    status_id: {
      color: '#000000',
      id: 'lNRkDKdPXq53iV94',
      name: 'BACKLOG',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746346602526,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '6817228d2398e8a9b97f2846',
    assignee_ids: [
      {
        id: 'Io5FmFfpo4zmv2wp',
        name: 'Fauzan',
      },
    ],
    created_at: 1746346637593,
    created_by: 0,
    date_end: 1747328400000,
    date_start: 1746723600000,
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: '312iunYceTS2Wseb',
    list_ids: [
      {
        id: 'kAa0ghxJLX1mKbgO',
        name: 'Research and Dev',
      },
    ],
    name: 'refetch test',
    parent_task_id: 'Fp7n1wNB5kd4G2sq',
    priority_id: {
      color: '#D56F16',
      id: 'GkdqL3ZBsL3XUDM7',
      name: 'MEDIUM',
    },
    product_id: {
      color: '#D23013',
      id: 'uhbRY6DSirLf2f3s',
      name: 'TALENTA',
    },
    progress: 0,
    status_id: {
      color: '#000000',
      id: 'lNRkDKdPXq53iV94',
      name: 'BACKLOG',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746346637593,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '681722a42398e8a9b97fa427',
    assignee_ids: [
      {
        id: 'Io5FmFfpo4zmv2wp',
        name: 'Fauzan',
      },
    ],
    created_at: 1746346660695,
    created_by: 0,
    date_end: 1747414800000,
    date_start: 1746723600000,
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'gborxesUt9vnHmAi',
    list_ids: [
      {
        id: 'kAa0ghxJLX1mKbgO',
        name: 'Research and Dev',
      },
    ],
    name: 'refetch 2',
    parent_task_id: 'Fp7n1wNB5kd4G2sq',
    priority_id: {
      color: '#D51616',
      id: 'hfqHjVUhRLQyBezK',
      name: 'HIGH',
    },
    product_id: {
      color: '#D23013',
      id: 'uhbRY6DSirLf2f3s',
      name: 'TALENTA',
    },
    progress: 0,
    status_id: {
      color: '#000000',
      id: 'lNRkDKdPXq53iV94',
      name: 'BACKLOG',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746346660695,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '681726b92398e8a9b987ee67',
    assignee_ids: [
      {
        id: 'MWzxqxyqUTYCnSL9',
        name: 'Alex',
      },
    ],
    created_at: 1746347705267,
    created_by: 0,
    date_end: 1746118800000,
    date_start: 1746118800000,
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'n0cocmtBoZrEqba9',
    list_ids: [
      {
        id: 'kAa0ghxJLX1mKbgO',
        name: 'Research and Dev',
      },
    ],
    name: 'oke',
    parent_task_id: 'Fp7n1wNB5kd4G2sq',
    priority_id: {
      color: '#D56F16',
      id: 'GkdqL3ZBsL3XUDM7',
      name: 'MEDIUM',
    },
    product_id: {
      color: '#9C13D2',
      id: '1OBzdu6cBSVK7pZ9',
      name: 'OFFICELESS',
    },
    progress: 0,
    status_id: {
      color: '#FB8D1E',
      id: 'bqPvMmVMSumQZ1mL',
      name: 'IN PROGRESS',
    },
    task_type_id: {
      color: '#D5D516',
      id: 'B93VwVE9n4S8jWFu',
      name: 'Meetings',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746347705267,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '68172bb22398e8a9b990f697',
    assignee_ids: [
      {
        id: 'MWzxqxyqUTYCnSL9',
        name: 'Alex',
      },
      {
        id: 'Io5FmFfpo4zmv2wp',
        name: 'Fauzan',
      },
      {
        id: 'Z3NmnmiO9OCZMokc',
        name: 'Aziza',
      },
    ],
    created_at: 1746348978281,
    created_by: 0,
    date_end: 1746810000000,
    date_start: 1746810000000,
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'miAUA3ydGsBzx1UR',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
      {
        id: 'kAa0ghxJLX1mKbgO',
        name: 'Research and Dev',
      },
    ],
    name: 'tes avatar',
    parent_task_id: '0',
    priority_id: {
      color: '#D51616',
      id: 'hfqHjVUhRLQyBezK',
      name: 'HIGH',
    },
    product_id: {
      color: '#9C13D2',
      id: '1OBzdu6cBSVK7pZ9',
      name: 'OFFICELESS',
    },
    progress: 0,
    status_id: {
      color: '#000000',
      id: 'lNRkDKdPXq53iV94',
      name: 'BACKLOG',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746348978281,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '68172c8d2398e8a9b991ebf5',
    assignee_ids: [
      {
        id: 'Io5FmFfpo4zmv2wp',
        name: 'Fauzan Fuady',
      },
      {
        id: 'MWzxqxyqUTYCnSL9',
        name: 'Alexander William',
      },
      {
        id: 'Z3NmnmiO9OCZMokc',
        name: 'Aziza',
      },
    ],
    created_at: 1746349197981,
    created_by: 0,
    date_end: 1746723600000,
    date_start: 1746032400000,
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'T4hNh6CnX6oz1utb',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
    ],
    name: 'test initials',
    parent_task_id: '0',
    priority_id: {
      color: '#D51616',
      id: 'hfqHjVUhRLQyBezK',
      name: 'HIGH',
    },
    product_id: {
      color: '#9C13D2',
      id: '1OBzdu6cBSVK7pZ9',
      name: 'OFFICELESS',
    },
    progress: 0,
    status_id: {
      color: '#000000',
      id: 'lNRkDKdPXq53iV94',
      name: 'BACKLOG',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746349197981,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '68172e012398e8a9b99690f4',
    assignee_ids: [
      {
        id: 'Z3NmnmiO9OCZMokc',
        name: 'Aziza',
      },
    ],
    created_at: 1746349569417,
    created_by: 0,
    date_end: 1746810000000,
    date_start: 1746723600000,
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'dawuw3YRwsUU4PMv',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
    ],
    name: 'refetch test 9',
    parent_task_id: '0',
    priority_id: {
      color: '#D56F16',
      id: 'GkdqL3ZBsL3XUDM7',
      name: 'MEDIUM',
    },
    product_id: {
      color: '#9C13D2',
      id: '1OBzdu6cBSVK7pZ9',
      name: 'OFFICELESS',
    },
    progress: 0,
    status_id: {
      color: '#1EA733',
      id: '2BZeEgG0tj1OYBQo',
      name: 'DONE',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746349569417,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '68172e432398e8a9b996d094',
    assignee_ids: [
      {
        id: 'Io5FmFfpo4zmv2wp',
        name: 'Fauzan Fuady',
      },
    ],
    created_at: 1746349635459,
    created_by: 0,
    date_end: 1747414800000,
    date_start: 1747242000000,
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'jFWXW2rueQ85wdea',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
    ],
    name: 'refecth child',
    parent_task_id: 'miAUQClaqgskx6P7',
    priority_id: {
      color: '#D56F16',
      id: 'GkdqL3ZBsL3XUDM7',
      name: 'MEDIUM',
    },
    product_id: {
      color: '#54C94D',
      id: 'PugQz8QjD6PyNivH',
      name: 'QONTAK',
    },
    progress: 0,
    status_id: {
      color: '#1E85FB',
      id: 'YjM6hHeaiWNpEHgx',
      name: 'IN REVIEW',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746349635459,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '68172ed42398e8a9b9974bc3',
    assignee_ids: [
      {
        id: 'MWzxqxyqUTYCnSL9',
        name: 'Alexander William',
      },
    ],
    created_at: 1746349780251,
    created_by: 0,
    date_end: 1746723600000,
    date_start: 1746637200000,
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'lNRkRxepq1BKiWHi',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
    ],
    name: 'child refetch task',
    parent_task_id: 'MWzxPyRIy98Bnw05',
    priority_id: {
      color: '#39BC11',
      id: 'B93VwX1GyukYjFDs',
      name: 'LOW',
    },
    product_id: {
      color: '#D23013',
      id: 'uhbRY6DSirLf2f3s',
      name: 'TALENTA',
    },
    progress: 0,
    status_id: {
      color: '#1E85FB',
      id: 'YjM6hHeaiWNpEHgx',
      name: 'IN REVIEW',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746349780251,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '68174a482398e8a9b9c8746b',
    assignee_ids: [
      {
        id: 'Io5FmFfpo4zmv2wp',
        name: 'Fauzan Fuady',
      },
    ],
    created_at: 1746356808472,
    created_by: 0,
    date_end: 1746810000000,
    date_start: 1746637200000,
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'miAUREtWt8ShxuYQ',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
      {
        id: 'miAGYVN4BqhNxq0T',
        name: 'Workflow Projects',
      },
    ],
    name: 'test description and attachments',
    parent_task_id: '0',
    priority_id: {
      color: '#D51616',
      id: 'hfqHjVUhRLQyBezK',
      name: 'HIGH',
    },
    product_id: {
      color: '#D23013',
      id: 'uhbRY6DSirLf2f3s',
      name: 'TALENTA',
    },
    progress: 0,
    status_id: {
      color: '#FB8D1E',
      id: 'bqPvMmVMSumQZ1mL',
      name: 'IN PROGRESS',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746356808472,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '68174b142398e8a9b9c95935',
    assignee_ids: [
      {
        id: 'Io5FmFfpo4zmv2wp',
        name: 'Fauzan Fuady',
      },
    ],
    attachments: [],
    created_at: 1746357012742,
    created_by: 0,
    date_end: 1746810000000,
    date_start: 1746723600000,
    description: {
      blocks: [
        {
          data: {
            level: 1,
            text: 'Head 1',
          },
          id: 'uPN3RvdI8G',
          tunes: {
            textVariantTune: '',
          },
          type: 'header',
        },
      ],
      time: 1746357012678,
      version: '2.31.0-rc.7',
    },
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'Z3Nmur8Bnz7yMqs3',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
    ],
    name: 'desc and attachment 2',
    parent_task_id: '0',
    priority_id: {
      color: '#D56F16',
      id: 'GkdqL3ZBsL3XUDM7',
      name: 'MEDIUM',
    },
    product_id: {
      color: '#D23013',
      id: 'uhbRY6DSirLf2f3s',
      name: 'TALENTA',
    },
    progress: 0,
    status_id: {
      color: '#1EA733',
      id: '2BZeEgG0tj1OYBQo',
      name: 'DONE',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746357012742,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '6817501c2398e8a9b9d29cd0',
    assignee_ids: [
      {
        id: 'MWzxqxyqUTYCnSL9',
        name: 'Alexander William',
      },
    ],
    attachments: [],
    created_at: 1746358300243,
    created_by: 0,
    date_end: 1746118800000,
    date_start: 1746118800000,
    description: {
      blocks: [],
      time: 1746358300177,
      version: '2.31.0-rc.7',
    },
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'qTulELenlcOi3nRs',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
    ],
    name: 'child 1',
    parent_task_id: '312iunYceTS2Wseb',
    priority_id: {
      color: '#D56F16',
      id: 'GkdqL3ZBsL3XUDM7',
      name: 'MEDIUM',
    },
    product_id: {
      color: '#9C13D2',
      id: '1OBzdu6cBSVK7pZ9',
      name: 'OFFICELESS',
    },
    progress: 0,
    status_id: {
      color: '#FB8D1E',
      id: 'bqPvMmVMSumQZ1mL',
      name: 'IN PROGRESS',
    },
    task_type_id: {
      color: '#D5D516',
      id: 'B93VwVE9n4S8jWFu',
      name: 'Meetings',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746358300243,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '6817502d2398e8a9b9d2f8e0',
    assignee_ids: [
      {
        id: 'MWzxqxyqUTYCnSL9',
        name: 'Alexander William',
      },
    ],
    attachments: [],
    created_at: 1746358317669,
    created_by: 0,
    date_end: 1746723600000,
    date_start: 1746637200000,
    description: {
      blocks: [],
      time: 1746358317608,
      version: '2.31.0-rc.7',
    },
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'VMiSNf7E8ltOXh3A',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
    ],
    name: 'child 4',
    parent_task_id: 'lNRkRxepq1BKiWHi',
    priority_id: {
      color: '#D51616',
      id: 'hfqHjVUhRLQyBezK',
      name: 'HIGH',
    },
    product_id: {
      color: '#9C13D2',
      id: '1OBzdu6cBSVK7pZ9',
      name: 'OFFICELESS',
    },
    progress: 0,
    status_id: {
      color: '#000000',
      id: 'lNRkDKdPXq53iV94',
      name: 'BACKLOG',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746358317669,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '68175dad2398e8a9b9ea305a',
    assignee_ids: [
      {
        id: 'Z3NmnmiO9OCZMokc',
        name: 'Aziza',
      },
    ],
    attachments: [],
    created_at: 1746361773498,
    created_by: 0,
    date_end: 1746810000000,
    date_start: 1746723600000,
    description: {
      blocks: [],
      time: 1746361773532,
      version: '2.31.0-rc.7',
    },
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'JrFEpZz2oEBgaOOX',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
    ],
    name: 'asdasd',
    parent_task_id: '0',
    priority_id: {
      color: '#D56F16',
      id: 'GkdqL3ZBsL3XUDM7',
      name: 'MEDIUM',
    },
    product_id: {
      color: '#9C13D2',
      id: '1OBzdu6cBSVK7pZ9',
      name: 'OFFICELESS',
    },
    progress: 0,
    status_id: {
      color: '#1E85FB',
      id: 'YjM6hHeaiWNpEHgx',
      name: 'IN REVIEW',
    },
    task_type_id: {
      color: '#D5D516',
      id: 'B93VwVE9n4S8jWFu',
      name: 'Meetings',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746361773498,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '68175de72398e8a9b9ead1a0',
    assignee_ids: [
      {
        id: 'Io5FmFfpo4zmv2wp',
        name: 'Fauzan Fuady',
      },
    ],
    attachments: [],
    created_at: 1746361831420,
    created_by: 0,
    date_end: 1746810000000,
    date_start: 1746723600000,
    description: {
      blocks: [],
      time: 1746361831389,
      version: '2.31.0-rc.7',
    },
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: '6XxyDUC5iPAag3Mg',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
    ],
    name: 'test refetch 2',
    parent_task_id: '0',
    priority_id: {
      color: '#D56F16',
      id: 'GkdqL3ZBsL3XUDM7',
      name: 'MEDIUM',
    },
    product_id: {
      color: '#D23013',
      id: 'uhbRY6DSirLf2f3s',
      name: 'TALENTA',
    },
    progress: 0,
    status_id: {
      color: '#000000',
      id: 'lNRkDKdPXq53iV94',
      name: 'BACKLOG',
    },
    task_type_id: {
      color: '#D5D516',
      id: 'B93VwVE9n4S8jWFu',
      name: 'Meetings',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746361831420,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '68175e282398e8a9b9ec26fd',
    assignee_ids: [
      {
        id: 'Io5FmFfpo4zmv2wp',
        name: 'Fauzan Fuady',
      },
    ],
    attachments: [],
    created_at: 1746361896755,
    created_by: 0,
    date_end: 1746810000000,
    date_start: 1746723600000,
    description: {
      blocks: [],
      time: 1746361896766,
      version: '2.31.0-rc.7',
    },
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'tSUBK36cuBcCyDtd',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
    ],
    name: 'refetch 3',
    parent_task_id: '0',
    priority_id: {
      color: '#D56F16',
      id: 'GkdqL3ZBsL3XUDM7',
      name: 'MEDIUM',
    },
    product_id: {
      color: '#D23013',
      id: 'uhbRY6DSirLf2f3s',
      name: 'TALENTA',
    },
    progress: 0,
    status_id: {
      color: '#FB8D1E',
      id: 'bqPvMmVMSumQZ1mL',
      name: 'IN PROGRESS',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746361896755,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '68175f152398e8a9b9ee76af',
    assignee_ids: [
      {
        id: 'Z3NmnmiO9OCZMokc',
        name: 'Aziza',
      },
    ],
    attachments: [],
    created_at: 1746362133031,
    created_by: 0,
    date_end: 1746810000000,
    date_start: 1746723600000,
    description: {
      blocks: [],
      time: 1746362133057,
      version: '2.31.0-rc.7',
    },
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'Io5F8aEIiVkpvoCn',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
    ],
    name: 'attachment 5',
    parent_task_id: '0',
    priority_id: {
      color: '#D51616',
      id: 'hfqHjVUhRLQyBezK',
      name: 'HIGH',
    },
    product_id: {
      color: '#1398D2',
      id: 'tSUBrfmc8WhBy3Z6',
      name: 'JURNAL',
    },
    progress: 0,
    status_id: {
      color: '#FB8D1E',
      id: 'bqPvMmVMSumQZ1mL',
      name: 'IN PROGRESS',
    },
    task_type_id: {
      color: '#D5D516',
      id: 'B93VwVE9n4S8jWFu',
      name: 'Meetings',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746362133031,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '68175fbe2398e8a9b9ef0700',
    assignee_ids: [
      {
        id: 'MWzxqxyqUTYCnSL9',
        name: 'Alexander William',
      },
      {
        id: 'Io5FmFfpo4zmv2wp',
        name: 'Fauzan Fuady',
      },
    ],
    attachments: [],
    created_at: 1746362302899,
    created_by: 0,
    date_end: 1746723600000,
    date_start: 1746723600000,
    description: {
      blocks: [],
      time: 1746362302933,
      version: '2.31.0-rc.7',
    },
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'W7YDjnwJfjiD0y1',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
    ],
    name: 'attachment 6',
    parent_task_id: '0',
    priority_id: {
      color: '#D51616',
      id: 'hfqHjVUhRLQyBezK',
      name: 'HIGH',
    },
    product_id: {
      color: '#9C13D2',
      id: '1OBzdu6cBSVK7pZ9',
      name: 'OFFICELESS',
    },
    progress: 0,
    status_id: {
      color: '#1E85FB',
      id: 'YjM6hHeaiWNpEHgx',
      name: 'IN REVIEW',
    },
    task_type_id: {
      color: '#D5D516',
      id: 'B93VwVE9n4S8jWFu',
      name: 'Meetings',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746362302899,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '681760962398e8a9b9efd0c7',
    assignee_ids: [
      {
        id: 'Z3NmnmiO9OCZMokc',
        name: 'Aziza',
      },
    ],
    attachments: [
      {
        filename: 'image 5.png',
        url: 'https://officeless-production-public.oss-ap-southeast-5.aliyuncs.com/27414/681760871771d-image-5.png',
      },
    ],
    created_at: 1746362518680,
    created_by: 0,
    date_end: 1747933200000,
    date_start: 1747846800000,
    description: {
      blocks: [],
      time: 1746362518674,
      version: '2.31.0-rc.7',
    },
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: '2BZeWEy7fReEY1PC',
    list_ids: [
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
    ],
    name: 'attachment 7',
    parent_task_id: '0',
    priority_id: {
      color: '#D51616',
      id: 'hfqHjVUhRLQyBezK',
      name: 'HIGH',
    },
    product_id: {
      color: '#9C13D2',
      id: '1OBzdu6cBSVK7pZ9',
      name: 'OFFICELESS',
    },
    progress: 0,
    status_id: {
      color: '#1E85FB',
      id: 'YjM6hHeaiWNpEHgx',
      name: 'IN REVIEW',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746362518680,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '681829ea2398e8a9b9b3f15f',
    assignee_ids: [
      {
        id: 'Io5FmFfpo4zmv2wp',
        name: 'Fauzan Fuady',
      },
    ],
    attachments: [],
    created_at: 1746414058563,
    created_by: 0,
    date_end: 1746464400000,
    date_start: 1746464400000,
    description: {
      blocks: [
        {
          data: {
            text: 'data assessment',
          },
          id: '7Ikd02D7vl',
          type: 'paragraph',
        },
      ],
      time: 1746414058296,
      version: '2.31.0-rc.7',
    },
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'T4hNgYaAOiF21eAc',
    list_ids: [
      {
        id: '7JjcVEyamNkFdr7e',
        name: 'data',
      },
    ],
    name: 'Data',
    parent_task_id: '0',
    priority_id: {
      color: '#D56F16',
      id: 'GkdqL3ZBsL3XUDM7',
      name: 'MEDIUM',
    },
    product_id: {
      color: '#9C13D2',
      id: '1OBzdu6cBSVK7pZ9',
      name: 'OFFICELESS',
    },
    progress: 0,
    status_id: {
      color: '#000000',
      id: 'lNRkDKdPXq53iV94',
      name: 'BACKLOG',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746414058563,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
  {
    _id: '68182a472398e8a9b9b6de59',
    assignee_ids: [
      {
        id: 'Io5FmFfpo4zmv2wp',
        name: 'Fauzan Fuady',
      },
    ],
    attachments: [],
    created_at: 1746414151487,
    created_by: 0,
    date_end: 1746378000000,
    date_start: 1746378000000,
    description: {
      blocks: [
        {
          data: {
            text: 'test againt',
          },
          id: 'J1NiMNzvhn',
          type: 'paragraph',
        },
      ],
      time: 1746414151337,
      version: '2.31.0-rc.7',
    },
    folder_id: {
      color: '#84C4FF',
      id: 'zYVAfGZ1JVUvc7YJ',
      name: 'Daily Operations',
    },
    folder_id_text: 'zYVAfGZ1JVUvc7YJ',
    id_task: 'N2HArgxO61NdzbEz',
    list_ids: [
      {
        id: '7JjcVEyamNkFdr7e',
        name: 'data',
      },
      {
        id: 'AeCdbf3zRhUlsDjN',
        name: 'List of Assessments',
      },
    ],
    name: 'data againt',
    parent_task_id: '0',
    priority_id: {
      color: '#D56F16',
      id: 'GkdqL3ZBsL3XUDM7',
      name: 'MEDIUM',
    },
    product_id: {
      color: '#9C13D2',
      id: '1OBzdu6cBSVK7pZ9',
      name: 'OFFICELESS',
    },
    progress: 0,
    status_id: {
      color: '#FB8D1E',
      id: 'bqPvMmVMSumQZ1mL',
      name: 'IN PROGRESS',
    },
    task_type_id: {
      color: '#5516D5',
      id: 'kAaT5TDU8f2JK7eh',
      name: 'Assessments',
    },
    team_id: {
      color: '#84C4FF',
      id: 'uhb89JeMrEQd2nfn',
      name: 'Solution Architects',
    },
    team_id_text: 'uhb89JeMrEQd2nfn',
    updated_at: 1746414151487,
    updated_by: 0,
    workspace_id: 'SxKfPgXcDS5bICvE',
  },
]
